name: daily heartbeat

on:
  schedule:
    # Runs at AM 9:00 GMT+09:00 every day
    - cron: '0 0 * * *'

jobs:
  # Job name called "heartbeat"
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run main.py
        run: python main.py --heartbeat
