name: weekly scraper

on:
  schedule:
    # Runs every hour PM 09:30 ~ 11:30 GMT+09:00 on Saturday
    # Runs every hour AM 00:30 ~ 02:30 GMT+09:00 on Sunday
    - cron: '30 12-17 * * 6'

jobs:
  # Job name called "scraper"
  scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit file
        run: |
          git config user.email '<github-actions[bot]@users.noreply.github.com>'
          git config user.name 'github-actions[bot]'
          git commit -m '[Bot] Update lotto.csv file' -a || echo 'Nothing to commit'

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
